---
repository: git@github.com:dcrec1/bok2.git
ansible_ssh_private_key_file: ~/.ssh/bok2.pem
ansible_ssh_user: ubuntu
app_name: bok2
app_path: /var/local/apps/bok2
rails_env: production
user: deploy
max_upload_size: 5m
environment_variables:
  DISABLE_SPRING: 1
