---
repository: git@github.com:dcrec1/pet_nativa.git
ansible_ssh_private_key_file: ~/.ssh/pet_nativa.pem
ansible_ssh_user: ubuntu
app_name: pet_nativa
app_path: /var/local/apps/pet_nativa
rails_env: production
user: deploy
max_upload_size: 5m
environment_variables:
  DISABLE_SPRING: 1
